name: Deploy docs

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/checkout@v3
              with:
                node-version: 16

            - run: npm ci

            - run: NODE_OPTIONS=--openssl-legacy-provider npm run build

            - name: Deploy storybook
              working-directory: ./packages/docs
              run: |
                touch storybook-static/.nojekyll 
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/matheusbarcc/callendar-design-system
                NODE_OPTIONS=--openssl-legacy-provider npm run deploy-storybook -- --ci -existing-output-dir=storybook-static
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}